apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-aks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-aks-api
  template:
    metadata:
      labels:
        app: mt-aks-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mt-aks-api
          image: arthureberle/mt-aks-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1000m
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mt-aks-api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: mt-aks-api
 ---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mt-aks-hpa
spec:
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mt-aks-api
  targetCPUUtilizationPercentage: 50 
