apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-aks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mt-aks-api
  template:
    metadata:
      labels:
        app: mt-aks-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mt-aks-api
          image: arthureberle/mt-aks-api:latest
          resources:
            requests:
              cpu: 500m
              memory: 3Gi
            limits:
              cpu: 1
              memory: 4Gi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mt-aks-api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: mt-aks-api
